import type { ChatMessage } from "./chatMessageRow";

export const mockMessages: ChatMessage[] = [
  {
    id: "msg-1",
    userId: 0,
    username: "System",
    text: "Welcome to Room 1",
    timestamp: Date.now() - 70000,
    type: "system",
  },
  {
    id: "msg-2",
    userId: 101,
    username: "Marc",
    text: "Marc joined the room",
    timestamp: Date.now() - 60000,
    type: "presence",
    presenceAction: "join",
  },
  {
    id: "msg-3",
    userId: 102,
    username: "Nick",
    text: "Nick joined the room",
    timestamp: Date.now() - 52000,
    type: "presence",
    presenceAction: "join",
  },
  {
    id: "msg-4",
    userId: 101,
    username: "Marc",
    text: "Crystal ball",
    timestamp: Date.now() - 45000,
    type: "guess",
  },
  {
    id: "msg-5",
    userId: 102,
    username: "Nick",
    text: "Axolotl?",
    timestamp: Date.now() - 30000,
    type: "guess",
  },
  {
    id: "msg-6",
    userId: 103,
    username: "Steph",
    text: "Igloo!",
    timestamp: Date.now() - 15000,
    isCorrectGuess: true,
    type: "guess",
  },
  {
    id: "msg-7",
    userId: 0,
    username: "System",
    text: "Steph guessed correctly! (+10 points)",
    timestamp: Date.now() - 14000,
    type: "system",
  },
  {
    id: "msg-8",
    userId: 102,
    username: "Nick",
    text: "Natalya left the room",
    timestamp: Date.now() - 9000,
    type: "presence",
    presenceAction: "leave",
  },
];
